# This represents the first pilot batch with AMTurk with 10 participants

# this file should contain something like
# mongodb://root:password@mongodb.com:27017/
# without any new line
path_mongo_db_url: "/home/paltenmo/Documents/url_with_credentials_mongodb_study_db.txt"

# where to store the evaluation of the users
# (e.g. the raw data from HRR, Google form and AMturk)
evaluation_folder: data/hrr/hum_v06/user_evaluation

# where to store the derived data of the users
# (e.g. the att. weights and the code heatmaps)
derived_data_folder: data/hrr/hum_v06/derived_data

# where to store the accepted user attention weights
accepted_data_folder: data/hrr/hum_v06/accepted_sessions

# google sheet behind the google form
spreadsheet_id: '1FHCdXedqxYlz1d8sZ3JRWXb2LMfnCkMclUj6VZM9zX8'
spreadsheet_range: 'Form Responses 1!A1:K100000'
# follow this guide to generate your credentials:
# https://daily-dev-tips.com/posts/python-read-data-from-a-google-sheet/
path_google_credentials: "/home/paltenmo/Documents/credentials_google_form.json"

# amazon mechanical turk
target_hit_id: 3INZSNUD801QR8B919YLGIN488H9DU #null # null means using the most recent
path_amturk_credentials: "/home/paltenmo/Documents/credentials_amturk.csv"

# number of hours to wait before considering a new record
n_hours_min_age: 4

# folder with metadata on the source files seen by the humans
# this is represented in a yaml file with info such as the tokenization,
# the buggy line, the prompt given to the human, etc
task_metadata_folder: /home/paltenmo/Documents/GITHUB_INTERN/CodeProjects/github-HRR/tasks/sensemaking_char